title: PixelPins
description: Pinball and Arcade LED Badges
show_downloads: false
markdown: GFM
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jemoji
